services:
  grails-app:
    build: .
    image: marachnid/groovybones:latest
    container_name: groovybones
    ports:
      - "8080:8080"
    environment:
      GRAILS_ENV: production
      APP_DOMAIN: "https://groovybones.net/"
      JAVA_OPTS: "-Xms256m -Xmx512m -XX:MaxMetaspaceSize=192m"
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped