services:
  grails-app:
    build: .
    image: marachnid/groovybones:latest
    container_name: groovybones
    ports:
      - "8080:8080"
    environment:
      GRAILS_ENV: production
      JAVA_OPTS: "-Xms256m -Xmx512m -XX:MaxMetaspaceSize=192m"
      DB_URL_PRD: ${DB_URL_PRD}
      DB_USERNAME_PRD: ${DB_USERNAME_PRD}
      DB_PASSWORD_PRD: ${DB_PASSWORD_PRD}

      API_KEY: ${API_KEY}

      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}

      USER_POOL_ID: ${USER_POOL_ID}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    restart: unless-stopped